### PR TITLE
Vaadin 7.5.3 and drag-selection

### PR DESCRIPTION
**Pull request by tomivirkki**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/components/88)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Notice that drag/batch selection might not work on sdm

**Comment by tepi** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[CHANGES.md, line 16 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/88#-JwzrgQUNJUf1Xa4rWI-)** ([raw file](https://github.com/vaadin/components/blob/7b5fdcbb47f8f1617a8b499a3d10a6a81e39419a/CHANGES.md#L16)):</sup>
typo

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/88)

**Comment by tomivirkki** [comment]
<sup>**[CHANGES.md, line 16 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/88#-JwzrgQUNJUf1Xa4rWI-)** ([raw file](https://github.com/vaadin/components/blob/7b5fdcbb47f8f1617a8b499a3d10a6a81e39419a/CHANGES.md#L16)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/88)

**Comment by manolo** [comment]
> Notice that drag/batch selection might not work on sdm

Why could it happen?

**Comment by tepi** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/88)

**Pull request merged**
