### PR TITLE
Fixed text-overflow: ellipsis for content and header/footer cells

### PR DESCRIPTION
**Pull request by tomivirkki**
Change-Id: I49f88d92c6583693eae743a6ec4aa571b24d3bf8

[Review on Reviewable](https://reviewable.io/reviews/vaadin/components/41)

### CODE REVIEW

**Comment by jounik** [comment]
I would rather not use the same method as in the Framework, since it assumes that all cell content should be inline-blocks.

Did you discuss the option of having a default text renderer which uses `<span>` elements? The header cells could use the same thing: https://trello.com/c/3HSmEC0m/73-default-text-renderer-for-all-cells-should-use-a-span-element-which-handles-text-overflow-ellipsis

Ideally I think we would like to use `display: flex;` for `.v-grid-row`, but then we need to handle the column widths somehow (or is it possible to disable CSS flex altogether?).

**Comment by anezthes** [comment]
We could use flex-grow (for percentage values) and width (for pixel values) to set the column widths.

**Comment by jounik** [comment]
Can we somehow make it backwards compatible with Framework 7 (i.e. browsers without flex box support)?

**Comment by anezthes** [comment]
I guess for those browsers, we either have to use padding and/or line-height for vertical alignment.

**Comment by Saulis** [comment]
Reviewed 8 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/41)

**Pull request merged**
