### PR TITLE
Changed focus style to reflect new design, also for detail rows

### PR DESCRIPTION
**Pull request by tepi**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/components/111)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Doesn't seem to work with multi select mode

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/111)

**Comment by tepi** [comment]
Fixed

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/111)

**Comment by tomivirkki** [comment]
Changes missing, other than that, LGTM.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/111)

**Comment by tepi** [comment]
note added to changes

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/111)

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/111)

**Pull request merged**
