### PR TITLE
Fix height update if grid is not attached

### PR DESCRIPTION
**Pull request by cwayfinder**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/components/60)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Missing the update to release notes

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/60)

**Comment by tomivirkki** [comment]
...and a test case

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/60)

**Comment by cwayfinder** [comment]
Fixes https://github.com/vaadin/components/issues/23

**Comment by tomivirkki** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/60)

**Pull request merged**
