### PR TITLE
Improve startup

### PR DESCRIPTION
**Pull request by manolo**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/components/56)

### CODE REVIEW

**Comment by cwayfinder** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/56#-Juu-nS27anC5pGUouZP)** ([raw file](https://github.com/vaadin/components/blob/3c25653cfbb12349cca6cd146b3c25639a7c5652/vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html#L6)):</sup>
this change breaks demo in production mode

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/56)

**Comment by amahdy** [comment]
<sup>**[tasks/gwt.js, line 90 \[r2\]](https://reviewable.io:443/reviews/vaadin/components/56#-JvUEFHrenkm1Jjtm7zl)** ([raw file](https://github.com/vaadin/components/blob/09af03139159e0a909807748e7ca99e881422360/tasks/gwt.js#L90)):</sup>
This does not remove <script src="sdm.js"></script> from demo.html. Causing 404.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/56)

**Comment by amahdy** [comment]
<sup>**[tasks/gwt.js, line 90 \[r2\]](https://reviewable.io:443/reviews/vaadin/components/56#-JvUEFHrenkm1Jjtm7zl)** ([raw file](https://github.com/vaadin/components/blob/09af03139159e0a909807748e7ca99e881422360/tasks/gwt.js#L90)):</sup>
does not remove src="sdm.js"**

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/56)

**Comment by amahdy** [comment]
<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html, line 40 \[r2\]](https://reviewable.io:443/reviews/vaadin/components/56#-JvUL8PnWSdIYm6ycjop)** ([raw file](https://github.com/vaadin/components/blob/68950b0ad598b5e9ce0088c2ab5012b2eeb1daf2/vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html#L40)):</sup>
To avoid all refactors and extra lines, maybe we can keep this code as following:
```js
function execute(id, cb) {
  HTMLImports.whenReady(cb(document.getElementById(id)));
}
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/56)

**Comment by amahdy** [comment]
For some reason, master loading time is between 750ms and 900ms
After this modifications, it loads between 1100ms and 1250ms

All tests pass, except two are pending forever. But this is the case in master as well.

**Comment by manolo** [comment]
do you mean demo.html? or you are using some other examples?

---

Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/56#-Juu-nS27anC5pGUouZP)** ([raw file](https://github.com/vaadin/components/blob/3c25653cfbb12349cca6cd146b3c25639a7c5652/vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html#L6)):</sup>
done

---

<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html, line 40 \[r2\]](https://reviewable.io:443/reviews/vaadin/components/56#-JvUL8PnWSdIYm6ycjop)** ([raw file](https://github.com/vaadin/components/blob/68950b0ad598b5e9ce0088c2ab5012b2eeb1daf2/vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html#L40)):</sup>
This is intentional, I don't want to maintain `execute`, since there is a public API doing the same `whenReady`, also I wan't examples teach the final user what is the correct way in polymer to do something in this case `whenReady`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/56)

**Comment by manolo** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[tasks/gwt.js, line 90 \[r2\]](https://reviewable.io:443/reviews/vaadin/components/56#-JvUEFHrenkm1Jjtm7zl)** ([raw file](https://github.com/vaadin/components/blob/09af03139159e0a909807748e7ca99e881422360/tasks/gwt.js#L90)):</sup>
Done

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/56)

**Comment by amahdy** [comment]
Reviewed 9 of 11 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/56)

**Comment by amahdy** [comment]
This issue appears with demo.html but not with single Grid.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/56)

**Pull request merged**
