### PR TITLE
Update column apidoc

### PR DESCRIPTION
**Pull request by cwayfinder**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/components/121)

### CODE REVIEW

**Comment by tomivirkki** [comment]
<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html, line 104 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/121#-Jy85C-GDlQJTvSupQ_P)** ([raw file](https://github.com/vaadin/components/blob/3ce77b8c0e4559c6d893ac8181cc43a9d1d68d1c/vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html#L104)):</sup>
Is this intentionally missing @type ?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/121)

**Comment by cwayfinder** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html, line 104 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/121#-Jy85C-GDlQJTvSupQ_P)** ([raw file](https://github.com/vaadin/components/blob/3ce77b8c0e4559c6d893ac8181cc43a9d1d68d1c/vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html#L104)):</sup>
The documentation generator works good for such properties without the @type annotation because it analyses the source code as well.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/121)

**Comment by cwayfinder** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html, line 104 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/121#-Jy85C-GDlQJTvSupQ_P)** ([raw file](https://github.com/vaadin/components/blob/3ce77b8c0e4559c6d893ac8181cc43a9d1d68d1c/vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html#L104)):</sup>
So it's not required from this point of view but maybe it's better to add the annotation

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/121)

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/121)

**Pull request merged**
