### PR TITLE
Some fixes to deploy snapshots.

### PR DESCRIPTION
**Pull request by manolo**
In this way we compare differences with master.
Also it will not fail if snapshot does not exist yet

[Review on Reviewable](https://reviewable.io/reviews/vaadin/components/105)

### CODE REVIEW

**Comment by tepi** [comment]
<sup>**[tasks/zip.js, line 38 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/105#-JxVI1GEleHxXSlx_cmC)** ([raw file](https://github.com/vaadin/components/blob/8684aa86767ac0e77aba4af32505f82328715b6f/tasks/zip.js#L38)):</sup>
Maybe we should not have vaadin.com hardcoded here? var hostName should be user?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/105)

**Comment by tepi** [comment]
<sup>**[tasks/zip.js, line 51 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/105#-JxVICPnnEuAZFwLIWVI)** ([raw file](https://github.com/vaadin/components/blob/8684aa86767ac0e77aba4af32505f82328715b6f/tasks/zip.js#L51)):</sup>
Maybe we should not have vaadin.com hardcoded here?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/105)

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tasks/zip.js, line 38 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/105#-JxVI1GEleHxXSlx_cmC)** ([raw file](https://github.com/vaadin/components/blob/8684aa86767ac0e77aba4af32505f82328715b6f/tasks/zip.js#L38)):</sup>
Done.

---

<sup>**[tasks/zip.js, line 51 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/105#-JxVICPnnEuAZFwLIWVI)** ([raw file](https://github.com/vaadin/components/blob/8684aa86767ac0e77aba4af32505f82328715b6f/tasks/zip.js#L51)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/105)

**Comment by tepi** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/105)

**Comment by tepi** [comment]
Looks good to me, but maybe someone else should take a look also.

**Comment by tomivirkki** [comment]
<sup>**[vaadin-components-package/README.md, line 51 \[r3\]](https://reviewable.io:443/reviews/vaadin/components/105#-JxZVzIfYXrjAJPfAht0)** ([raw file](https://github.com/vaadin/components/blob/52e7103521da1cf60e5a3128e3fa9373c7447329/vaadin-components-package/README.md#L51)):</sup>
Do we need the -snapshot tag at all?
Would bower install --save vaadin-components#master work the same without us having to maintain the tag?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/105)

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[vaadin-components-package/README.md, line 51 \[r3\]](https://reviewable.io:443/reviews/vaadin/components/105#-JxZVzIfYXrjAJPfAht0)** ([raw file](https://github.com/vaadin/components/blob/52e7103521da1cf60e5a3128e3fa9373c7447329/vaadin-components-package/README.md#L51)):</sup>
master is synchronised with latest release. We could though avoid the '-snapshot' suffix and deploy snapshots as master. I don't see any problem, if other people agree. Let's ask in the stand-up

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/105)

**Comment by jounik** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[vaadin-components-package/README.md, line 51 \[r3\]](https://reviewable.io:443/reviews/vaadin/components/105#-JxZVzIfYXrjAJPfAht0)** ([raw file](https://github.com/vaadin/components/blob/52e7103521da1cf60e5a3128e3fa9373c7447329/vaadin-components-package/README.md#L51)):</sup>
I agree, master can represent the snapshot. That will be the case anyway once (if) we move to using the development repo as the Bower repo as well.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/105)

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/105)

**Pull request merged**
