### PR TITLE
Header/footer get rendered even if new ds is empty (fixes #24)

### LINKED ISSUE #24: Clearing the Grid's data source makes the grid disappear
This snippet will hide the first grid on the page

var ds = [[1]];
var grid = document.querySelector("v-grid");
grid.data.source = ds;
grid.then(function(){
  ds.splice(0, 1);
  grid.data.clearCache();
});

### PR DESCRIPTION
**Pull request by tomivirkki**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/components/59)

### CODE REVIEW

**Comment by tepi** [comment]
<sup>**[vaadin-components-gwt/src/main/java/com/vaadin/components/grid/ViolatedGrid.java, line 92 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/59#-JvxBaEDq_YM0_d-URta)** ([raw file](https://github.com/vaadin/components/blob/b51cec713a6cb0d6e30531663eec1089b3c2740a/vaadin-components-gwt/src/main/java/com/vaadin/components/grid/ViolatedGrid.java#L92)):</sup>
What's this 3?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/59)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-components-gwt/src/main/java/com/vaadin/components/grid/ViolatedGrid.java, line 92 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/59#-JvxBaEDq_YM0_d-URta)** ([raw file](https://github.com/vaadin/components/blob/b51cec713a6cb0d6e30531663eec1089b3c2740a/vaadin-components-gwt/src/main/java/com/vaadin/components/grid/ViolatedGrid.java#L92)):</sup>
If Grid has only the header row visible, the divider gets hidden because of overflow:hidden. Added 3 extra pixels to the height so it shows.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/59)

**Comment by tepi** [comment]
<sup>**[vaadin-components-gwt/src/main/java/com/vaadin/components/grid/ViolatedGrid.java, line 92 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/59#-JvxBaEDq_YM0_d-URta)** ([raw file](https://github.com/vaadin/components/blob/b51cec713a6cb0d6e30531663eec1089b3c2740a/vaadin-components-gwt/src/main/java/com/vaadin/components/grid/ViolatedGrid.java#L92)):</sup>
IMO this is prone to fail since the 3px is dependent on the theme. Maybe we could live with the divider not showing in this case, or alternatively measure the actual required height from the browser.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/59)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-components-gwt/src/main/java/com/vaadin/components/grid/ViolatedGrid.java, line 92 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/59#-JvxBaEDq_YM0_d-URta)** ([raw file](https://github.com/vaadin/components/blob/b51cec713a6cb0d6e30531663eec1089b3c2740a/vaadin-components-gwt/src/main/java/com/vaadin/components/grid/ViolatedGrid.java#L92)):</sup>
Removed. If the missing divider is an issue, let's handle it later in a separate patch.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/59)

**Pull request merged**
