### PR TITLE
Remove unneeded checkbox opacity (fixes #32)

### LINKED ISSUE #32: Wrong checkbox style state
- In the demo, go to example "9" (Selection)
- Select an element then unselect it: the checkbox color weight is higher than others.
- Now scroll a bit down, you will see other checkboxes with the same style.

Basically the reused row (checkbox) keeps the style state which is wrong.

### PR DESCRIPTION
**Pull request by amahdy**
Default color (opacity 0.3) is already specified. 0.6 opacity is different and never seen in the grid because it will be always overriden by the blue color. So practically it's not needed.

[Review on Reviewable](https://reviewable.io/reviews/vaadin/components/36)

### CODE REVIEW

**Comment by tomivirkki** [comment]
+1 for tabindex="-1". This is however a Grid issue and should be reported/fixed there (also).

**Comment by amahdy** [comment]
There is even a slightly bigger issue when you use "TAB" in Vaadin Grid: https://dev.vaadin.com/ticket/18347

**Comment by amahdy** [comment]
-1 for tabindex="-1". It will limit the usability for keyboard gurus.

**Comment by jounik** [comment]
> -1 for tabindex="-1". It will limit the usability for keyboard gurus.

Grid has keyboard navigation and selection by other means (row focus using arrow keys + space for selecting). Having the individual checkboxes focusable reduces the usability.

**Comment by amahdy** [comment]
To add `tabindex=-1`
Possible solutions:

1. Add custom `MultiSelectionRenderer`
  - It requires custom `SelectionModelMulti` and `SelectionMode` as well.
  - `MultiSelectionRenderer` code is different than HEAD in vaadin/grid.

For this solution, `checkBox.setTabIndex(-1)` is needed in `init()` (old code) or `createWidget()` (new code).
2. Fix the issue from vaadin/grid and include a newer widgetset.

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html, line 338 \[r2\]](https://reviewable.io:443/reviews/vaadin/components/36#-JtCVsul7qxbW6kkjCBh)** ([raw file](https://github.com/vaadin/components/blob/9e88cb4a14d6726d885f1e3afa50c0e70e55eb0f/vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html#L338)):</sup>
Is this needed, how does the user know the checkbox selected when using keyboard?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/36)

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/36)

**Pull request merged**
