### PR TITLE
Remove value generator

### PR DESCRIPTION
**Pull request by Saulis**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/components/12)

### CODE REVIEW

**Comment by cwayfinder** [comment]
lgtm

**Comment by jounik** [comment]
LGTM

**Comment by Saulis** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- CHANGES.md @ r1
- vaadin-components-gwt/src/main/java/com/vaadin/components/grid/config/JSColumn.java @ r2
- vaadin-components-gwt/src/main/java/com/vaadin/components/grid/data/GridDataSource.java @ r2
- vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java @ r2
- vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html @ r2
- vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html @ r1
- vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/12)

**Comment by cwayfinder** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java, line 72 \[r2\]](https://reviewable.io:443/reviews/vaadin/components/12#-JqJyFaQAwdkKwuuh5m3)** ([raw file](https://github.com/vaadin/components/blob/320de25bdf3639a42ed6e991ee1c116c6416de1c/vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java#L72)):</sup>
`test` comment

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/12)

**Comment by Saulis** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- CHANGES.md @ r1
- vaadin-components-gwt/src/main/java/com/vaadin/components/grid/config/JSColumn.java @ r2
- vaadin-components-gwt/src/main/java/com/vaadin/components/grid/data/GridDataSource.java @ r2
- vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java @ r2
- vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html @ r2
- vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html @ r1
- vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html @ r2

---

<sup>**[vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java, line 72 \[r2\]](https://reviewable.io:443/reviews/vaadin/components/12#-JqJyFaQAwdkKwuuh5m3)** ([raw file](https://github.com/vaadin/components/blob/320de25bdf3639a42ed6e991ee1c116c6416de1c/vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java#L72)):</sup>
:shipit: 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/12)

**Comment by jounik** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java, line 72 \[r2\]](https://reviewable.io:443/reviews/vaadin/components/12#-JqJyFaQAwdkKwuuh5m3)** ([raw file](https://github.com/vaadin/components/blob/320de25bdf3639a42ed6e991ee1c116c6416de1c/vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java#L72)):</sup>
First I thought that was Mr. Paddington, but apparently it’s some sort of rodent? Am I missing some common knowledge about emojis here?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/12)

**Comment by Saulis** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java, line 72 \[r2\]](https://reviewable.io:443/reviews/vaadin/components/12#-JqJyFaQAwdkKwuuh5m3)** ([raw file](https://github.com/vaadin/components/blob/320de25bdf3639a42ed6e991ee1c116c6416de1c/vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java#L72)):</sup>
http://www.quora.com/GitHub/What-is-the-significance-of-the-Ship-It-squirrel

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/12)

**Pull request merged**
