### PR TITLE
Update documentation.

### PR DESCRIPTION
**Pull request by Saulis**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/components/40)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Cell/RowClassGenerator and column.renderer are functions that take a Cell as parameter. They should be documented so that they are accessible in the doc viewer.

**Comment by Saulis** [comment]
See docs live here: http://vaadin.github.io/components-apidoc/

**Comment by Saulis** [comment]
Docs added for Cell and RowClassGenerators, see http://vaadin.github.io/components-apidoc/

**Comment by jounik** [comment]
"Row" has the following description: “Represents a grid header/footer row configuration.”

It doesn’t seem correct when I followed the links from cellClassGenerator -> Cell -> Row

**Comment by Saulis** [comment]
Reworded with 'Object referencing to a row and it's data.'

**Comment by tomivirkki** [comment]
<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html, line 348 \[r4\]](https://reviewable.io:443/reviews/vaadin/components/40#-JsxwTWRdvzM1_oaZlug)** ([raw file](https://github.com/vaadin/components/blob/1a32116661638f92ae9869ea3eedd22ff307032a/vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html#L348)):</sup>
Should say ...the <v-grid> element

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/40)

**Comment by Saulis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html, line 348 \[r4\]](https://reviewable.io:443/reviews/vaadin/components/40#-JsxwTWRdvzM1_oaZlug)** ([raw file](https://github.com/vaadin/components/blob/1a32116661638f92ae9869ea3eedd22ff307032a/vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html#L348)):</sup>
"Reference to the element. " you means?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/40)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html, line 348 \[r4\]](https://reviewable.io:443/reviews/vaadin/components/40#-JsxwTWRdvzM1_oaZlug)** ([raw file](https://github.com/vaadin/components/blob/1a32116661638f92ae9869ea3eedd22ff307032a/vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html#L348)):</sup>
Apparently reviewable removed the v-grid tag from the middle.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/40)

**Comment by Saulis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html, line 348 \[r4\]](https://reviewable.io:443/reviews/vaadin/components/40#-JsxwTWRdvzM1_oaZlug)** ([raw file](https://github.com/vaadin/components/blob/1a32116661638f92ae9869ea3eedd22ff307032a/vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html#L348)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/40)

**Pull request merged**
