### PR TITLE
Fixed failing tests when using ?dom=shadow

### PR DESCRIPTION
**Pull request by tepi**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/components/94)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html, line 192 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/94#-Jx54Xfi_K4oBQRNPHbi)** ([raw file](https://github.com/vaadin/components/blob/517324ea22ec6912b0e914d00e94166e8eb7407b/vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html#L192)):</sup>
Why was this expect removed? grid.querySelector => qLocal/qLigth should work here.

---

<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html, line 192 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/94#-Jx55FrB9iTTsSBCG7rs)** ([raw file](https://github.com/vaadin/components/blob/de9abc3556ecb75836a372926a356b8cc4dbce8f/vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html#L192)):</sup>
qaLocal(selector)[0] is longer way of saying qLocal(selector)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/94)

**Comment by tepi** [comment]
<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html, line 192 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/94#-Jx54Xfi_K4oBQRNPHbi)** ([raw file](https://github.com/vaadin/components/blob/517324ea22ec6912b0e914d00e94166e8eb7407b/vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html#L192)):</sup>
Oops.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/94)

**Comment by tepi** [comment]
<sup>**[vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html, line 192 \[r1\]](https://reviewable.io:443/reviews/vaadin/components/94#-Jx55FrB9iTTsSBCG7rs)** ([raw file](https://github.com/vaadin/components/blob/de9abc3556ecb75836a372926a356b8cc4dbce8f/vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html#L192)):</sup>
Changed

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/94)

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/components/94)

**Pull request merged**
